/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error": "#ba1a1a",
        "tertiary-container": "#6b7586",
        "on-tertiary-container": "#fdfcff",
        "background": "#f8f9fa",
        "on-primary-container": "#fefcff",
        "on-secondary-fixed": "#001c39",
        "outline": "#727785",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#3d4756",
        "tertiary-fixed": "#d9e3f6",
        "secondary-fixed": "#d4e3ff",
        "on-secondary": "#ffffff",
        "primary": "#3b82f6",
        "on-secondary-container": "#003c70",
        "surface-container": "#edeeef",
        "tertiary-fixed-dim": "#bdc7d9",
        "on-surface-variant": "#424754",
        "surface-tint": "#3b82f6",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "tertiary": "#525d6c",
        "on-surface": "#191c1d",
        "primary-container": "#dbeafe",
        "inverse-on-surface": "#f0f1f2",
        "secondary-container": "#64a8fe",
        "outline-variant": "#c2c6d6",
        "on-primary-fixed-variant": "#004395",
        "inverse-primary": "#adc6ff",
        "surface-container-highest": "#e1e3e4",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#a4c9ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "surface": "#f8f9fa",
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "secondary": "#0060ac",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004883",
        "on-tertiary-fixed": "#121c2a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "sans": ["Inter", "sans-serif"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.019em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.021em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "-0.006em", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "-0.011em", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.022em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "-0.014em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
